In [1]:
%matplotlib inline

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import itertools

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, SimpleRNN, Conv1D, Flatten, Dense

# Title

## Heading

кодиране на входни данни

In [3]:
rnn = Sequential([
    Input(shape=(50, 5)),
    
    SimpleRNN(64, return_sequences=True),
    SimpleRNN(64, return_sequences=True),
    SimpleRNN(32, return_sequences=True),
    Flatten(),
    
    Dense(42, activation='relu'),
    Dense(1000, activation='softmax'),
])

In [4]:
rnn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 50, 64)            4480      
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 50, 64)            8256      
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 50, 32)            3104      
                                                                 
 flatten (Flatten)           (None, 1600)              0         
                                                                 
 dense (Dense)               (None, 42)                67242     
                                                                 
 dense_1 (Dense)             (None, 1000)              43000     
                                                                 
Total params: 126,082
Trainable params: 126,082
Non-trai

In [9]:
conv_nn = Sequential([
    Input(shape=(50, 5)),
    
    Conv1D(64, kernel_size=3, activation='relu'),
    Conv1D(64, kernel_size=3, activation='relu'),
    Conv1D(32, kernel_size=3, activation='relu'),
    Flatten(),
    
    Dense(42, activation='relu'),
    Dense(1000, activation='softmax'),
])

In [10]:
conv_nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 48, 64)            1024      
                                                                 
 conv1d_1 (Conv1D)           (None, 46, 64)            12352     
                                                                 
 conv1d_2 (Conv1D)           (None, 44, 32)            6176      
                                                                 
 flatten_1 (Flatten)         (None, 1408)              0         
                                                                 
 dense_2 (Dense)             (None, 42)                59178     
                                                                 
 dense_3 (Dense)             (None, 1000)              43000     
                                                                 
Total params: 121,730
Trainable params: 121,730
Non-tr

In [54]:
a = np.arange(9).reshape(3,3)
a = tf.Variable(a, dtype=tf.float32)
a = tf.expand_dims(a, 0)

In [55]:
a

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]], dtype=float32)>

In [59]:
def create_const_conv(filters, size, weight, bias):
    """
    Create 1d convolution layer with constant weights and biases.
    """
    kernel_initializer = tf.keras.initializers.Constant(value=weight)
    bias_initializer = tf.keras.initializers.Constant(value=bias)

    conv1d = Conv1D(
        filters=filters,
        kernel_size=size, 
        kernel_initializer=kernel_initializer, 
        bias_initializer=bias_initializer,
    )
    
    return conv1d

In [64]:
filters = [1, 2] 
sizes = [1, 3]
weights = [1, 2]
biases = [0, 1]
cartesian_products = itertools.product(filters, sizes, weights, biases)

for f, s, w, b in cartesian_products:
    print('-' * 80)
    print(f'n_filters = {f}, kernel_size = {s}, weights = {w}, biases = {b}')
    conv1d = create_const_conv(filters=f, size=s, weight=w, bias=b)
    print(conv1d(a).numpy())

--------------------------------------------------------------------------------
n_filters = 1, kernel_size = 1, weights = 1, biases = 0
[[[ 3.]
  [12.]
  [21.]]]
--------------------------------------------------------------------------------
n_filters = 1, kernel_size = 1, weights = 1, biases = 1
[[[ 4.]
  [13.]
  [22.]]]
--------------------------------------------------------------------------------
n_filters = 1, kernel_size = 1, weights = 2, biases = 0
[[[ 6.]
  [24.]
  [42.]]]
--------------------------------------------------------------------------------
n_filters = 1, kernel_size = 1, weights = 2, biases = 1
[[[ 7.]
  [25.]
  [43.]]]
--------------------------------------------------------------------------------
n_filters = 1, kernel_size = 3, weights = 1, biases = 0
[[[36.]]]
--------------------------------------------------------------------------------
n_filters = 1, kernel_size = 3, weights = 1, biases = 1
[[[37.]]]
------------------------------------------------------